
### Variables
@port = 3000
@id = 66182a2ca7a315fd991a4790



### Get todos

GET http://localhost:{{port}}/api/todos

### Create a todo

POST http://localhost:{{port}}/api/todos
Content-Type: application/json

{
  "item": "Finish the Assignment"
}

### Toggle completed status of a todo

PUT http://localhost:{{port}}/api/todos/{{id}}


